version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    restart: always
